name: Just no idea

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install

      - name: Build UI
        run: pnpm run build --filter ui

      - name: Build Blog
        run: pnpm run build --filter blog
